// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// greedy_distance_cpp
List greedy_distance_cpp(NumericVector a, NumericVector b, double target_val);
RcppExport SEXP _bridges_greedy_distance_cpp(SEXP aSEXP, SEXP bSEXP, SEXP target_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type target_val(target_valSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_distance_cpp(a, b, target_val));
    return rcpp_result_gen;
END_RCPP
}
// greedy_bfb_distance_cpp
List greedy_bfb_distance_cpp(NumericVector a, NumericVector b, double penalty);
RcppExport SEXP _bridges_greedy_bfb_distance_cpp(SEXP aSEXP, SEXP bSEXP, SEXP penaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type penalty(penaltySEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_bfb_distance_cpp(a, b, penalty));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bridges_greedy_distance_cpp", (DL_FUNC) &_bridges_greedy_distance_cpp, 3},
    {"_bridges_greedy_bfb_distance_cpp", (DL_FUNC) &_bridges_greedy_bfb_distance_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_bridges(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
