# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Greedy block-adjustment distance (no history)
NULL

greedy_distance_cpp <- function(a, b, target_val = 2.0) {
    .Call(`_bridges_greedy_distance_cpp`, a, b, target_val)
}

greedy_bfb_distance_cpp <- function(a, b, penalty = 0.0) {
    .Call(`_bridges_greedy_bfb_distance_cpp`, a, b, penalty)
}

